services:
  webapi:
    build:
      context: ../../src/webapi
      dockerfile: Dockerfile
    container_name: webapi-app
    ports:
      - "${WEBAPI_HOST_PORT}:${WEBAPI_CONTAINER_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Mongo=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST_DOCKER}:${MONGO_PORT}/admin?authSource=admin
      - ASPNETCORE_URLS=http://+:${WEBAPI_CONTAINER_PORT}
    networks:
      - infra_default

  webapp:
    build:
      context: ../../src/WebApp
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: webapp-app
    ports:
      - "${WEBAPP_HOST_PORT}:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - webapi
    networks:
      - infra_default

networks:
  infra_default:
    external: truecd..
    